export const CREATE_TODO_ITEM = 'CREATE_TODO_ITEM';
export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM';
export const CHECK_TODO_ITEM = 'CHECK_TODO_ITEM';
export const UNCHECK_TODO_ITEM = 'UNCHECK_TODO_ITEM';
export const GET_TODO_ITEMS = 'GET_TODO_ITEMS';